services:
  - type: web
    name: meetroom
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm ci && npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: meetroom
          property: host
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: QUEUE_CONNECTION
        value: sync
      - key: REVERB_APP_ID
        value: local
      - key: REVERB_APP_KEY
        value: local
      - key: REVERB_APP_SECRET
        value: local
      - key: REVERB_HOST
        value: 0.0.0.0
      - key: REVERB_PORT
        value: 8080
      - key: REVERB_SCHEME
        value: http
      - key: REVERB_PUBLIC_WS_URL
        value: ""
      - key: CLOUDFLARE_TURN_KEY_ID
        value: d620458570a991df270da6f309d52e3b
      - key: CLOUDFLARE_TURN_KEY_SECRET
        value: 2c362dbe9099c5fe1a7ec2e3b020d888eaaa8b54754239c21a586a5a2a8ffda7

  - type: worker
    name: reverb
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: php artisan reverb:start --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: REVERB_APP_ID
        value: local
      - key: REVERB_APP_KEY
        value: local
      - key: REVERB_APP_SECRET
        value: local
      - key: REVERB_HOST
        value: 0.0.0.0
      - key: REVERB_PORT
        value: 8080
      - key: REVERB_SCHEME
        value: http