services:
  - type: web
    name: meetroom
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_KEY
        value: base64:8ECU46ybC3U/9KjkKJmZbw+RyH5IMq4mR8PDesf04HY=
      - key: APP_URL
        fromService:
          type: web
          name: meetroom
          property: host
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: meetroom-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: meetroom-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: meetroom-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: meetroom-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: meetroom-db
          property: password
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: QUEUE_CONNECTION
        value: sync
      - key: REVERB_APP_ID
        value: local
      - key: REVERB_APP_KEY
        value: local
      - key: REVERB_APP_SECRET
        value: local
      - key: REVERB_HOST
        value: 0.0.0.0
      - key: REVERB_PORT
        value: "8080"
      - key: REVERB_SCHEME
        value: http
      - key: REVERB_PUBLIC_WS_URL
        value: ""
      - key: CLOUDFLARE_TURN_KEY_ID
        value: d620458570a991df270da6f309d52e3b
      - key: CLOUDFLARE_TURN_KEY_SECRET
        value: 2c362dbe9099c5fe1a7ec2e3b020d888eaaa8b54754239c21a586a5a2a8ffda7

databases:
  - name: meetroom-db
    databaseName: meetroom
    user: meetroom
    plan: free
